apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: ryrw1frzb-python 
  janus-idp.io/tekton: ryrw1frzb-python
  backstage.io/kubernetes-id: ryrw1frzb-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ryrw1frzb-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml