apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ryrw1frzb-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ryrw1frzb-python 
  name: ryrw1frzb-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ryrw1frzb-python 
